name: Debricked Scan

on:
  push:
  pull_request:

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Debricked CLI
        run: |
          curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz \
          | tar -xz debricked

          chmod +x debricked
          ./debricked --version

      - name: Run Debricked Scan
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
        run: |
          ./debricked scan . \
            -t "$DEBRICKED_TOKEN" \
            -c "$(git rev-parse HEAD)"
